config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root 'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'contact' => 'static_pages#contact'
  resources :users, only: [:show, :edit, :update]
  resources :tests, only: [:index, :create, :show, :update]
  
  namespace :admin do
    root 'users#index'
    resources :lessons
    resources :users
    resources :tests, only: [:index, :show, :update]
  end

end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  has_many :questions, dependent: :destroy
  accepts_nested_attributes_for :questions, 
    reject_if: :reject_questions, allow_destroy: true
  validates :name, presence: true

  private
  def reject_questions(attributes)
    attributes[:content].blank?
  end
end

app/controllers/admin/lessons_controller.rb
class Admin::LessonsController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_user
  include UsersHelper

  def index
    @lessons = Lesson.paginate page: params[:page], per_page: 20
  end

  def new
    @lesson = Lesson.new
  end

  def create
    @lesson = Lesson.new lesson_params
    if @lesson.save
      flash[:info] = "Created new lesson: #{@lesson.name}"
      redirect_to admin_lesson_path(@lesson)
    else
      render :new
    end
  end

  def edit
    @lesson = Lesson.find params[:id]
  end

  def update
    @lesson = Lesson.find params[:id]
    if @lesson.update(lesson_params)
      flash[:info] = "Updated lesson!"
      redirect_to admin_lesson_path(@lesson)
    else
      render :edit
    end
  end

  def show
    @lesson = Lesson.find params[:id]
    @questions = @lesson.questions
  end

  def destroy
    Lesson.find(params[:id]).destroy
    flash[:success] = "Deleted lesson."
    redirect_to admin_lessons_path
  end

  private
  def lesson_params
    params.require(:lesson).permit :name, :time,
      questions_attributes: [:content, :id, 
        options_attributes: [:content, :correct, :_destroy, :id]]
  end
end

app/helpers/admin/lessons_helper.rb
module Admin::LessonsHelper
  def get_character_index index
    (65 + index).chr
  end
end

app/views/admin/lessons/_form.html.erb
<%= form_for [:admin, @lesson] do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
    <%= f.label :time %>
    <%= f.number_field :time, class: 'form-control' %>
  </p>
  <%= f.fields_for :questions do |builder| %>
    <%= render 'question_fields', f: builder %>
  <% end %>
  <p>
    <%= link_to_add_fields "Add question", f, :questions %>
  </p>
  <p>
    <%= f.submit :Submit, class: 'btn btn-primary col-md-12' %>
  </p>
<% end %>

app/views/admin/lessons/_lesson.html.erb
<tr>
  <td><%= lesson.name %></td>
  <td><%= lesson.time %></td>
  <td><%= link_to "Edit", edit_admin_lesson_path(lesson) %></td>
  <td><%= link_to "Delete", admin_lesson_path(lesson), data: {confirm: "Do you want to delete lesson #{lesson.name}?"}, method: :delete %></td>
</tr>

app/views/admin/lessons/_option.html.erb
<% f.each_with_index do |option, index| %>
  <p>
    <div class="col-md-1"><%= option.correct ? "O" : "X" %></div>
    <div class="col-md-1">
      <%= get_character_index index %>: 
    </div>
    <%= option.content %>
  </p>
<% end %>

app/views/admin/lessons/_option_fields.html.erb
<div class="row", class="fields">
  <%= f.label :Option, class: 'col-sm-2' %>
  <%= f.text_field :content, class: 'col-sm-7' %>
  <%= f.check_box :correct, class: 'col-sm-2' %>
  <%= f.hidden_field :_destroy %>
  <%= link_to_remove_fields :Remove, f %>
</div>

app/views/admin/lessons/_question.html.erb
<% @questions.each do |question| %>
  <p>Question</p>
  <div><%= question.content %></div>
  <div>
    <%= render 'option', f: question.options %>
  </div>
<% end %>

app/views/admin/lessons/_question_fields.html.erb
<%= f.label :question %>
<%= f.text_area :content, rows: 3, class: 'form-control' %>
<%= f.fields_for :options do |builder| %>
  <%= render 'option_fields', f: builder %>
<% end %>
<div class="col-md-12" id="add-answer">
  <%= link_to_add_fields "Add answer", f, :options %>
</div>

app/views/admin/lessons/edit.html.erb
<div class="row">
  <div class="box">
    <div class="col-lg-12">
      <hr>
      <h2 class="intro-text text-center"><strong>Edit lesson</strong></h2>
      <hr>
      <div>
        <%= render partial: 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/admin/lessons/index.html.erb
<% provide(:title, 'All lessons') %>
<div class="row">
  <div class="box">
    <div class="col-lg-12">
      <hr>
      <h2 class="intro-text text-center"><strong>All lessons</strong></h2>
      <hr>
      <%= link_to "Add new lesson", new_admin_lesson_path, class: "edit-btn btn btn-primary col-md-4 col-md-offset-4" %>
    </div>
    <ul>
      <div class="col-md-offset-9"><%= will_paginate %></div>
      <table class="table">
        <thead>
          <tr>
            <th>Name</th>
            <th>Time per test (minutes)</th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <%= render @lessons %>
        </tbody>
      </table>
      <div class="col-md-offset-9"><%= will_paginate %></div>
    </ul>
  </div>
</div>

app/views/admin/lessons/new.html.erb
<div class="row">
  <div class="box">
    <div class="col-lg-12">
      <hr>
      <h2 class="intro-text text-center"><strong>Create new lesson</strong></h2>
      <hr>
      <div>
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/admin/lessons/show.html.erb
<div class="row">
  <div class="box">
    <div class="col-lg-12">
      <hr>
      <h2 class="intro-text text-center"><strong>Lesson information</strong></h2>
      <hr>
      <div class="col-md-3 col-md-offset-1">
        <p>Name: <%= @lesson.name %></p>
        <p>Time: <%= @lesson.time %></p>
      </div>
      <div class="col-md-offset-4">
        <%= render 'question' %>
      </div>
    </div>
  </div>
</div>